### ISSUE TITLE
member page not showing all certs

### ISSUE THREAD

**Issue by KeithRichardLee** [ModernAppsNinja/modernappsninja.github.io#214]
**Describe the bug**
My member page https://modernappsninjas.github.io/KeithRichardLee/ is not showing all certs. Only showing vSphere with Tanzu 101 and 201. Missing the 301 cert

**Comment by afewell** [comment]
Hi @KeithRichardLee  it should be good now. I have a minor bug where race conditions occasionally cause hugo builds to fail ... it doesnt impact the source repo content so as soon as anything triggers another build it fixes everything ... I am looking into fixes for the root cause so you might see this happen occasionally until I get it nailed down. Thanks!
