### ISSUE TITLE
Completed vSphere with Tanzu 201.  Received Badge in Badgr. Does not show in my modern apps ninja home page

### ISSUE THREAD

**Issue by dyablonski** [ModernAppsNinja/modernappsninja.github.io#723]
Please describe your issue or question in detail. Please be careful to include all the relevant information we will need to resolve the issue, including the url of any pages related to your issue or question.

**Comment by afewell** [comment]
Hi @dyablonski sorry for my delay,  I did update your page so that the cert does show, but there are a couple other bugs I found right now that I still need to get to so while its functional not everything is working right yet.

You can see your cert on your page by clicking on the "My Certificates" link on the top of your page, and that should be working fine. The problems are that, on your homepage I have the template set to only display 3 records and it shows a "See All" button that links to the certs page. The problem is that the link on the "See All" button is wrong, it links to the "/cert" directory when it should link to the "/certs" directory. Its not hard to fix, but its the same problem on every member page and its waiting for me to finish a different workflow that will allow me to apply fixes to all the affected pages. 

So it does work for now if you click on the my certificates link, and I am working to fix the issue with the incorrect link on the "See All" button as soon as I can. 

Thanks!
